//////////////////////////// NonTermEnum ////////////////////////////

enum class NonTermEnum
{
    /*0*/ [Accept2],
    /*1*/ OptionList,
    /*2*/ CmdLine,
    /*3*/ FileName,
    /*4*/ Option,
    /*5*/ ParseDataParamList,
    /*6*/ ParseDataParam,
    /*7*/ EnumFileParam,
    /*8*/ TermEnumParamList,
    /*9*/ TermEnumParam,
    /*10*/ ClassName,
    /*11*/ NonTermEnumParamList,
    /*12*/ NonTermEnumParam,
    /*13*/ ProdEnumParamList,
    /*14*/ ProdEnumParam,
    /*15*/ ReduceFuncParamList,
    /*16*/ ReduceFuncParam,
    /*17*/ StaticDFAParamList,
    /*18*/ StaticDFAParam,
    /*19*/ StaticParseTableParamList,
    /*20*/ StaticParseTableParam,
    /*21*/ CanonicalParam,
    /*22*/ ConflictReportParamList,
    /*23*/ ConflictReportParam,
    /*24*/ HelpParamList,
    /*25*/ HelpParam,
    /*26*/ CmdLineGrammarParam
};

constexpr char const* const StringifyEnumNonTermEnum[] =
{
    /*0*/ "[Accept2]",
    /*1*/ "OptionList",
    /*2*/ "CmdLine",
    /*3*/ "FileName",
    /*4*/ "Option",
    /*5*/ "ParseDataParamList",
    /*6*/ "ParseDataParam",
    /*7*/ "EnumFileParam",
    /*8*/ "TermEnumParamList",
    /*9*/ "TermEnumParam",
    /*10*/ "ClassName",
    /*11*/ "NonTermEnumParamList",
    /*12*/ "NonTermEnumParam",
    /*13*/ "ProdEnumParamList",
    /*14*/ "ProdEnumParam",
    /*15*/ "ReduceFuncParamList",
    /*16*/ "ReduceFuncParam",
    /*17*/ "StaticDFAParamList",
    /*18*/ "StaticDFAParam",
    /*19*/ "StaticParseTableParamList",
    /*20*/ "StaticParseTableParam",
    /*21*/ "CanonicalParam",
    /*22*/ "ConflictReportParamList",
    /*23*/ "ConflictReportParam",
    /*24*/ "HelpParamList",
    /*25*/ "HelpParam",
    /*26*/ "CmdLineGrammarParam"
};
