// This is a generated file.
// Copyright is in `CmdLineParser.gr` - see that file for details.

//////////////////////////// TermEnum ////////////////////////////

enum TermEnum
{
    /*0*/ TE_TokenError,
    /*1*/ TE_TokenEOF,
    /*2*/ TE_option,
    /*3*/ TE_parameter,
    /*4*/ TE_integer,
    /*5*/ TE_fileName,
    /*6*/ TE_className,
    /*7*/ TE_msgCode,
    /*8*/ TE_colon,
    /*9*/ TE_opConfigFile,
    /*10*/ TE_opTableTypeLR,
    /*11*/ TE_opTableTypeLALR,
    /*12*/ TE_opTableTypeCLR,
    /*13*/ TE_opParseData,
    /*14*/ TE_opNamespaces,
    /*15*/ TE_opEnumFile,
    /*16*/ TE_opEnumClasses,
    /*17*/ TE_opEnumStrings,
    /*18*/ TE_opTermEnum,
    /*19*/ TE_opNonTermEnum,
    /*20*/ TE_opProdEnum,
    /*21*/ TE_opReduceFunc,
    /*22*/ TE_opStaticDFA,
    /*23*/ TE_opStaticParseTable,
    /*24*/ TE_opCanonical,
    /*25*/ TE_opConflictReport,
    /*26*/ TE_opNoWarnings,
    /*27*/ TE_opNotes,
    /*28*/ TE_opStats,
    /*29*/ TE_opHelp,
    /*30*/ TE_opQuietMode,
    /*31*/ TE_opVersion,
    /*32*/ TE_opCLGrammar,
    /*33*/ TE_fileNameParam,
    /*34*/ TE_namespaceNameParam,
    /*35*/ TE_classNameParam,
    /*36*/ TE_stackNameParam,
    /*37*/ TE_prefixParam,
    /*38*/ TE_stringParam,
    /*39*/ TE_optionParam,
    /*40*/ TE_messageParam,
    /*41*/ TE_dfaParam,
    /*42*/ TE_linesParam,
    /*43*/ TE_labelsParam,
    /*44*/ TE_pointsParam,
    /*45*/ TE_displayParam,
    /*46*/ TE_string
};
