// This is a generated file.
// Copyright is in `CmdLineParser.gr` - see that file for details.

//////////////////////////// TermEnum ////////////////////////////

namespace XC
{

enum class TermEnum
{
    /*0*/ TokenError,
    /*1*/ TokenEOF,
    /*2*/ option,
    /*3*/ parameter,
    /*4*/ integer,
    /*5*/ fileName,
    /*6*/ className,
    /*7*/ msgCode,
    /*8*/ colon,
    /*9*/ opConfigFile,
    /*10*/ opTableTypeLR,
    /*11*/ opTableTypeLALR,
    /*12*/ opTableTypeCLR,
    /*13*/ opParseData,
    /*14*/ opNamespaces,
    /*15*/ opEnumFile,
    /*16*/ opEnumClasses,
    /*17*/ opEnumStrings,
    /*18*/ opTermEnum,
    /*19*/ opNonTermEnum,
    /*20*/ opProdEnum,
    /*21*/ opReduceFunc,
    /*22*/ opStaticDFA,
    /*23*/ opStaticParseTable,
    /*24*/ opCanonical,
    /*25*/ opConflictReport,
    /*26*/ opNoWarnings,
    /*27*/ opNotes,
    /*28*/ opStats,
    /*29*/ opHelp,
    /*30*/ opQuietMode,
    /*31*/ opVersion,
    /*32*/ opCLGrammar,
    /*33*/ fileNameParam,
    /*34*/ namespaceNameParam,
    /*35*/ classNameParam,
    /*36*/ stackNameParam,
    /*37*/ prefixParam,
    /*38*/ stringParam,
    /*39*/ optionParam,
    /*40*/ messageParam,
    /*41*/ dfaParam,
    /*42*/ linesParam,
    /*43*/ labelsParam,
    /*44*/ pointsParam,
    /*45*/ displayParam,
    /*46*/ string
};

constexpr char const* const StringifyEnumTermEnum[] =
{
    /*0*/ "TokenError",
    /*1*/ "TokenEOF",
    /*2*/ "option",
    /*3*/ "parameter",
    /*4*/ "integer",
    /*5*/ "fileName",
    /*6*/ "className",
    /*7*/ "msgCode",
    /*8*/ "colon",
    /*9*/ "opConfigFile",
    /*10*/ "opTableTypeLR",
    /*11*/ "opTableTypeLALR",
    /*12*/ "opTableTypeCLR",
    /*13*/ "opParseData",
    /*14*/ "opNamespaces",
    /*15*/ "opEnumFile",
    /*16*/ "opEnumClasses",
    /*17*/ "opEnumStrings",
    /*18*/ "opTermEnum",
    /*19*/ "opNonTermEnum",
    /*20*/ "opProdEnum",
    /*21*/ "opReduceFunc",
    /*22*/ "opStaticDFA",
    /*23*/ "opStaticParseTable",
    /*24*/ "opCanonical",
    /*25*/ "opConflictReport",
    /*26*/ "opNoWarnings",
    /*27*/ "opNotes",
    /*28*/ "opStats",
    /*29*/ "opHelp",
    /*30*/ "opQuietMode",
    /*31*/ "opVersion",
    /*32*/ "opCLGrammar",
    /*33*/ "fileNameParam",
    /*34*/ "namespaceNameParam",
    /*35*/ "classNameParam",
    /*36*/ "stackNameParam",
    /*37*/ "prefixParam",
    /*38*/ "stringParam",
    /*39*/ "optionParam",
    /*40*/ "messageParam",
    /*41*/ "dfaParam",
    /*42*/ "linesParam",
    /*43*/ "labelsParam",
    /*44*/ "pointsParam",
    /*45*/ "displayParam",
    /*46*/ "string"
};

} // namespace XC
